version: '3.8'

services:
  frontend:
    build:
      context: ./piFrontEnd
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - fullstack_network
    depends_on:
      - backend

  backend:
    build:
      context: ./piBackEnd
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - fullstack_network

networks:
  fullstack_network:
    driver: bridge
