version: '3'
frontend:
  build:
    context: ./piFrontEnd
    dockerfile: Dockerfile
  ports:
    - "5000:5173"
  networks:
    - fullstack_network
  depends_on:
    - backend


  backend:
    build:
      context: ./piBackEnd
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Le backend sera accessible sur localhost:3001
    networks:
      - fullstack_network

networks:
  fullstack_network:
    driver: bridge
