version: '3'
services:
  frontend:
    build:
      context: ./piFrontEnd  # Répertoire contenant le Dockerfile pour le frontend
      dockerfile: Dockerfile  # Utiliser le Dockerfile du frontend
    ports:
      - "3001:3000"  # Mapper le port 3000 du container sur 3001 de la machine hôte
    networks:
      - fullstack_network
    depends_on:
      - backend  # Attendre que le backend soit prêt avant de démarrer le frontend

  backend:
    build:
      context: ./piBackEnd  # Répertoire contenant le Dockerfile pour le backend
      dockerfile: Dockerfile  # Utiliser le Dockerfile du backend
    ports:
      - "3000:3000"  # Mapper le port 3000 du container sur 3000 de la machine hôte
    networks:
      - fullstack_network

networks:
  fullstack_network:
    driver: bridge
